name: Növényöntözés email értesítő

on:
  schedule:
    - cron: '0 14 * * *'  # minden nap 18:00-kor UTC idő szerint
  workflow_dispatch:     # manuális indítás lehetősége

jobs:
  send-reminder-email:
    runs-on: ubuntu-latest

    steps:
    - name: Kód klónozása
      uses: actions/checkout@v3

    - name: Python beállítása
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Függőségek telepítése
      run: |
        python -m pip install --upgrade pip

    - name: Email küldő script futtatása
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python send_reminder.py